### ISSUE TITLE
API returns unexpected None for actors

### ISSUE THREAD

**Issue by plotski** [dbr/tvdb_api#73] opened 2020-02-27 09:31 UTC
```python
>>> Tvdb(cache=False, actors=True)['Death Valley (2014)']
[...]
DEBUG:urllib3.connectionpool:https://api.thetvdb.com:443 "GET /series/286509/actors HTTP/1.1" 404 21
DEBUG:tvdb_api:loadurl: https://api.thetvdb.com/series/286509/actors lid=en
DEBUG:tvdb_api:response:
DEBUG:tvdb_api:{'Error': 'not found'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/foo/code/pythonBits/venv/lib/python3.7/site-packages/tvdb_api.py", line 1182, in __getitem__
    sid = self._nameToSid(key)
  File "/home/foo/code/pythonBits/venv/lib/python3.7/site-packages/tvdb_api.py", line 1168, in _nameToSid
    self._getShowData(selected_series['id'], self.config['language'])
  File "/home/foo/code/pythonBits/venv/lib/python3.7/site-packages/tvdb_api.py", line 1110, in _getShowData
    self._parseActors(sid)
  File "/home/foo/code/pythonBits/venv/lib/python3.7/site-packages/tvdb_api.py", line 1057, in _parseActors
    for curActorItem in actorsEt:
TypeError: 'NoneType' object is not iterable
```

This should be easy to fix by wrapping the for loop at line 1057 in a `if isinstance(actorsEt, abc.Iterable)`.

**Comment by dbr** [comment] 2020-05-11 14:04
Strangely I get a show-not-found error with `actors=True` (works fine without):

```
>>> Tvdb()["Death Valley (2014)"]
<Show 'Death Valley (2014)' (containing 1 seasons)>
>>> Tvdb(actors=True)["Death Valley (2014)"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dbr/code/tvdb_api/tvdb_api.py", line 1163, in __getitem__
    sid = self._nameToSid(key)
  File "/Users/dbr/code/tvdb_api/tvdb_api.py", line 1152, in _nameToSid
    self._getShowData(selected_series['id'], self.config['language'])
  File "/Users/dbr/code/tvdb_api/tvdb_api.py", line 1094, in _getShowData
    self._parseActors(sid)
  File "/Users/dbr/code/tvdb_api/tvdb_api.py", line 1038, in _parseActors
    actorsEt = self._getetsrc(self.config['url_actorsInfo'] % (sid))
  File "/Users/dbr/code/tvdb_api/tvdb_api.py", line 888, in _getetsrc
    src = self._loadUrl(url, language=language)
  File "/Users/dbr/code/tvdb_api/tvdb_api.py", line 852, in _loadUrl
    raise tvdb_error("%s" % error)
tvdb_api.tvdb_error: not found
```

**Comment by dbr** [comment] 2020-05-11 14:08
Not too sure why your code didn't throw the tvdb_error exception and instead continues - this should be handled in the `_loadUrl` method

**Comment by dbr** [comment] 2020-05-11 14:17
Ahh, the NoneType error was fixed as part of the changes in tvdb_api 3.0

So the problem is just
https://api.thetvdb.com/series/286509/actors
is returning the not found error instead of an empty list

**Comment by plotski** [comment] 2020-05-11 14:26
I'm using version 2.0, maybe that explains it?

I haven't tried 3.0 yet due to the API key requirement.

**Comment by dbr** [comment] 2020-05-11 14:30
Yep - 2.0 vs 3.0 explains the slightly different error produced, but either way it's caused by a problem with the API response from TheTVDB

**Comment by mueslo** [comment] 2020-06-06 00:53
It would still be prudent to work around this exception in `tvdb_api`. So when it throws an exception, please just return None or an empty list, please. The further down this has to be mitigated, the uglier it becomes (e.g. two instances of Imdb(), where one includes actors, and another doesn't, etc...)

**Comment by dbr** [comment] 2020-06-15 10:54
Summarised this in #85 - shall close this as there's a few duplicates and it's a bit hard to keep track. Thanks all!

**Closed by dbr** 2020-06-15 10:54 UTC
Labels: bug
